### PR TITLE
Includes rk loader for .img release

### PR DESCRIPTION
**Pull request by 7Ji**
Sticking with the KISS philosophy of Arch Linux, this project never goes one step further on deciding things needed by users, anything included or configured are for the image to be bootable and connectable to network, so users can decide which packages they want and configurations they want after the first boot. And even if that is too much, there is -pkgs.tar  release so users can just pacstrap from ground up like Arch Linux.

On to bootloader, it is not included in .img release as I wanted to give users biggest freedom to decide the allocation of bootloader device, boot device and root device. I made the choice to not include the rk loader as that met my use case: for my OPi5, I used the SPI flash for rk bootloader, and a NVMe drive as boot device and root device, and I wanted 0 byte wasted on my SSD. That was natural, but deemed inconvenient by some, especially those expecting the image would boot just like those WhateverPi / Armbian / etc images previously used by them.

As such, I'm opening this PR as a sort-of voting place. This is marked as draft as actually 0 codes have been added to implement it.

What do you guys think?
@Integral-Tech @DaveWK

### CODE REVIEW

**Comment by Integral-Tech** [comment]
For my OPi5 Plus, I also used the SPI flash for rk bootloader. IMO it’s not necessary to include rk loader.

**Comment by mgfm99** [comment]
I'd welcome the bootloader in the image. I see the point about space, but I just find it more flexible to have the bootloader in place. Like you both, my main use scenario is using SPI flash and NVME.

**Comment by DaveWK** [comment]
I'd be content with just a partition table that had zero's where the bootloader pieces should go. I believe that should compress better? Including a bootloader does incurr the cost of release management of the bootloader

**Comment by 7Ji** [comment]
Closed as this was implemented, although not in this PR.

From now on there will be [a nightly release](https://github.com/7Ji/orangepi5-archlinuxarm/releases/tag/nightly) with freshly built images and archives, including the following types of downloads to choose from:
  - `*-base.img`, similar to the previous `*-img`, set to using opi5's dtb, without rkloader
  - `*-5.img`, with opi5's rkloader, set to use opi5's dtb
  - `*-5_sata.img`. with opi5's rkloader with m.2 remux set to sata, set to use opi5's dtb + sata dtbo
  - `*-5b.img`, with opi5b's rkloader, set to use opi5b's dtb
  - `*-5_plus.img`, with opi5plus's rkloader, set to use opi5plus'dtb
  - `*-root.tar`, similar to the previous `*-root.tar`, containing the whole rootfs inside the above images, useful to just decompress to a disk you've partitioned by yourself

`*-pkgs.tar` was removed, in favour of using kernel packages directly from [my repo](https://github.com/7Ji/archrepo)

There're of course other changes as I've switched to [a new cross-builder written from ground up](https://github.com/7Ji/orangepi5-archlinuxarm/blob/master/cross_nobuild.sh) , ditched the old QEMU-based wrapper around the native ALARM builder. The README.md is not updated to document them yet. But a quick summary of the things changed in new images:
 - Timezone is now UTC instead of Asia/Shanghai
 - Timesyncd enabled by default
 - Locale is now en_US.UTF-8 instead of en_GB.UTF-8, while en_GB.UTF-8 and zh_CN.UTF-8 are neither enabled. (previously all 3 of them are enabled, and locale is set to use en_GB)
 - sshd_config kept the default, not allowing root password login
 - root does not have password and can't be logged in if not set, the alarm user in wheel group with password `alarm_please_change_me` is the only way you would login to a newly deployed system.
 - My repo added to pacman.conf, so you can just `pacman -Syu` to upgrade kernels and firmware.

**Pull request closed without merging**
