### PR TITLE
README.md: add btrfs prompt

### PR DESCRIPTION
**Pull request by Integral-Tech**

### CODE REVIEW

**Comment by 7Ji** [comment]
The failed check has nothing to do with this PR, it was caused by the newly added `linux-firmware-orangepi` package, I'll handle this PR after I fix the building problem

**Comment by 7Ji** [comment]
Also, the subvolume arg is only needed if the user is using a non-default volume. If they're using the default subvolume then it is not needed.

And I feel the need to explain the submodule concept a little. Because users might think it could also affect the `/boot/` path if they're using a non CoW subvolume for `/boot` but don't understand the fact that subvolume is just a namespace like folder, so in fact it won't be affected.

The following log is from another box, since I'm not using btrfs for `/boot` on opi, as I don't trust the outdated u-boot provided by the vendor to be robust enough to handle btrfs `/boot`

```
nomad7ji@bpi ~> cat /proc/cmdline 
root=/dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1 rootflags=subvol=root rw audit=0
nomad7ji@bpi ~> cat /boot/extlinux/extlinux.conf
LABEL   Arch Linux
LINUX   /boot/vmlinuz-linux-aarch64-7ji
INITRD  /boot/initramfs-linux-aarch64-7ji.img
FDT     /boot/dtbs/linux-aarch64-7ji/amlogic/meson-sm1-bananapi-m5.dtb
APPEND  root=/dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1 rootflags=subvol=root rw audit=0
nomad7ji@bpi ~> sudo btrfs subvolume list /
ID 256 gen 54719 top level 5 path root
ID 257 gen 54719 top level 5 path home
ID 258 gen 54719 top level 5 path var
ID 259 gen 45914 top level 5 path swap
ID 260 gen 54714 top level 5 path boot
ID 261 gen 30479 top level 5 path qbittorrent
nomad7ji@bpi ~> grep boot /etc/fstab 
/dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1             /boot           btrfs           rw,subvol=/boot 0 0
```

**Comment by 7Ji** [comment]
Sorry, after some testing in opi5's u-boot after using it for server for several months staright, I found its u-boot does not support btrfs at all, so we can just ignore the btrfs `/boot` idea altogether, only only care about btrfs `/`

**Comment by Integral-Tech** [comment]
> Also, the subvolume arg is only needed if the user is using a non-default volume. If they're using the default subvolume then it is not needed.
> 
> And I feel the need to explain the subvolume concept a little. Because users might think it could also affect the `/boot/` path if they're using a non CoW subvolume for `/boot` but don't understand the fact that subvolume is just a namespace like folder, so in fact it won't be affected.
> 
> The following log is from another box, since I'm not using btrfs for `/boot` on opi, as I don't trust the outdated u-boot provided by the vendor to be robust enough to handle btrfs `/boot`
> 
> ```
> nomad7ji@bpi ~> cat /proc/cmdline 
> root=/dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1 rootflags=subvol=root rw audit=0
> nomad7ji@bpi ~> cat /boot/extlinux/extlinux.conf
> LABEL   Arch Linux
> LINUX   /boot/vmlinuz-linux-aarch64-7ji
> INITRD  /boot/initramfs-linux-aarch64-7ji.img
> FDT     /boot/dtbs/linux-aarch64-7ji/amlogic/meson-sm1-bananapi-m5.dtb
> APPEND  root=/dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1 rootflags=subvol=root rw audit=0
> nomad7ji@bpi ~> sudo btrfs subvolume list /
> ID 256 gen 54719 top level 5 path root
> ID 257 gen 54719 top level 5 path home
> ID 258 gen 54719 top level 5 path var
> ID 259 gen 45914 top level 5 path swap
> ID 260 gen 54714 top level 5 path boot
> ID 261 gen 30479 top level 5 path qbittorrent
> nomad7ji@bpi ~> grep boot /etc/fstab 
> /dev/disk/by-id/mmc-AJTD4R_0x32c2f457-part1             /boot           btrfs           rw,subvol=/boot 0 0
> ```

I think it would be better to explain the subvolume concept, since Arch Wiki does not provide any information about u-boot.

**Comment by 7Ji** [comment]
> I think it would be better to explain the subvolume concept, since Arch Wiki does not provide any information about u-boot. Arch Wiki only explains common x86-64 bootloaders.

But since opi5's u-boot does not support btrfs at all, the earliest code that supports btrfs lies within kernel itself, and it's only kernel's cmdline that both affects the kernel bootup path and could be seen by u-boot (but u-boot does not understand the `APPEND` line, it just passes it to kernel). So what's learnt from x86-64 Arch could still be applied to the configs here, only difference is the place to set kernel argumen't.

**Comment by Integral-Tech** [comment]
> > I think it would be better to explain the subvolume concept, since Arch Wiki does not provide any information about u-boot. Arch Wiki only explains common x86-64 bootloaders.
> 
> But since opi5's u-boot does not support btrfs at all, the earliest code that supports btrfs lies within kernel itself, and it's only kernel's cmdline that both affects the kernel bootup path and could be seen by u-boot (but u-boot does not understand the `APPEND` line, it just passes it to kernel). So what's learnt from x86-64 Arch could still be applied to the configs here, only difference is the place to set kernel argument.

Since opi5's u-boot does not support Btrfs at all, add this explanation won't make users think it could also affect the /boot path.

**Comment by 7Ji** [comment]
Okay, go ahead with your changes

**Comment by Integral-Tech** [comment]
> Okay, go ahead with your changes

If you think the PR is okay now, could you merge it? :)

**Comment by 7Ji** [comment]
I'm waiting for the latest Github Actions CI job to finish. After that's finished and building deps are cached, your PR won't trigger another full rebuild, and the beautiful green check mark will appear sooner on your merge commit message : )

**Pull request merged**
